name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
      
    - name: Run extension tests
      run: npm test
      
    - name: Run linter
      run: npm run lint
      
    - name: Install blog dependencies
      run: cd blog && npm install
      
    - name: Run blog tests
      run: npm run test:blog
